#!/usr/bin/env bash
# (Re)write the F-Droid repo's config.yml from config.yaml + the keystore sidecar.
#
# `fdroid init` writes a huge commented template with no identity and no
# passwords; this replaces it with the small, correct file for this box. It is
# safe to re-run — it is the single place the repo's identity is defined:
#
#   fdroid.url / name / description / keystore-alias   -> repo identity + signing key
#   directories.fdroid-keystore(.pass)                 -> keystore + its password
#
# The generated file contains the keystore password, so it is written 0600 and
# lives on the big disk with the key, never in git.
#
# Usage: scripts/fdroid-config.sh
if [ -z "${BASH_VERSION:-}" ]; then
  exec bash "$0" "$@"
fi

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# shellcheck source=../config.sh
source "$ROOT/config.sh"

REPO_DIR="${FDROID_REPO:-$(cfg_get directories fdroid-repo || true)}"
KEYSTORE="${FDROID_KEYSTORE:-$(cfg_get directories fdroid-keystore || true)}"
ALIAS="${FDROID_KEY_ALIAS:-$(cfg_get fdroid keystore-alias || true)}"
URL="$(cfg_get fdroid url || true)"
NAME="$(cfg_get fdroid name || true)"
DESC="$(cfg_get fdroid description || true)"

for pair in "directories.fdroid-repo:$REPO_DIR" "directories.fdroid-keystore:$KEYSTORE" \
            "fdroid.keystore-alias:$ALIAS" "fdroid.url:$URL" "fdroid.name:$NAME"; do
  if [ -z "${pair#*:}" ]; then
    echo "!! ${pair%%:*} is not set in config.yaml (see config.example.yaml)" >&2
    exit 1
  fi
done

PASSFILE="$KEYSTORE.pass"
if [ ! -f "$PASSFILE" ]; then
  echo "!! no $PASSFILE — create the key first: scripts/fdroid-keystore.sh" >&2
  exit 1
fi
PASS="$(tr -d '\n' <"$PASSFILE")"

mkdir -p "$REPO_DIR"
OUT="$REPO_DIR/config.yml"
umask 077
cat >"$OUT" <<EOF
# GENERATED by scripts/fdroid-config.sh — do not hand-edit.
# Identity comes from /data/android/config.yaml; re-run the script to update.
sdk_path: /opt/android-sdk
# The JDK isn't on the container's PATH, so point fdroidserver straight at it.
java_paths:
  '21': /opt/java/openjdk

repo_url: $URL
repo_name: $NAME
repo_description: ${DESC:-$NAME}

# Paths as seen inside the fdroid:local container (see scripts/fdroid.sh).
keystore: /keystore
repo_keyalias: $ALIAS
keystorepass: $PASS
keypass: $PASS
EOF
chmod 600 "$OUT"
echo "wrote $OUT (0600) — repo '$NAME' at $URL, signed by alias '$ALIAS'"
