"""Run the second indexer — the F-Droid repo — after a store index rebuild.

``tools/publish`` and ``tools/reindex`` own ``repo/index.json``; the signed
F-Droid index is generated by ``scripts/fdroid-publish.sh`` one directory up
(sync APKs -> project metadata -> ``fdroid update -c``). This module is the thin
seam between the two so a single command keeps both outputs in sync, whether it
is invoked by ``build.sh`` or by hand.

Failure behaviour is deliberate: the F-Droid step is **advisory**. The store
index has already been written by the time it runs, so an uninitialized repo, a
missing ``fdroid:local`` image or a signing error prints a warning and leaves the
caller's exit status alone. Losing the F-Droid mirror must never make a
successful publish look like a failed one; rerun ``scripts/fdroid-publish.sh``
once the repo is set up and the two indexes converge again.

Knobs: ``FDROID_PUBLISH=0`` skips it entirely, ``FDROID_PUBLISH_SCRIPT``
overrides the script path (the default assumes the store lives at
``<android>/store``).
"""

from __future__ import annotations

import os
import subprocess
import sys

_STORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SCRIPT = os.path.join(
    os.path.dirname(_STORE_DIR), "scripts", "fdroid-publish.sh"
)


def script_path() -> str:
    return os.environ.get("FDROID_PUBLISH_SCRIPT") or DEFAULT_SCRIPT


def update() -> bool:
    """Regenerate the F-Droid index. Returns True when it actually ran clean."""
    if os.environ.get("FDROID_PUBLISH") == "0":
        print("fdroid: skipped (FDROID_PUBLISH=0)")
        return False

    script = script_path()
    if not os.access(script, os.X_OK):
        print(f"fdroid: skipped — no publisher at {script}", file=sys.stderr)
        return False

    print(f"fdroid: updating the F-Droid repo ({script})")
    result = subprocess.run([script])
    if result.returncode != 0:
        print(
            "fdroid: repo update failed — the BAM Store index above is still valid; "
            "rerun scripts/fdroid-publish.sh to resync.",
            file=sys.stderr,
        )
        return False
    return True
